# Freiburg Groceries class order from ImageFolder (alphabetical).
CLASS_NAMES = [
    "BEANS",
    "CAKE",
    "CANDY",
    "CEREAL",
    "CHIPS",
    "CHOCOLATE",
    "COFFEE",
    "CORN",
    "FISH",
    "FLOUR",
    "HONEY",
    "JAM",
    "JUICE",
    "MILK",
    "NUTS",
    "OIL",
    "PASTA",
    "RICE",
    "SODA",
    "SPICES",
    "SUGAR",
    "TEA",
    "TOMATO_SAUCE",
    "VINEGAR",
    "WATER",
]

DISPLAY_NAMES = {
    "BEANS": "Beans",
    "CAKE": "Cake",
    "CANDY": "Candy",
    "CEREAL": "Cereal",
    "CHIPS": "Chips",
    "CHOCOLATE": "Chocolate",
    "COFFEE": "Coffee",
    "CORN": "Corn",
    "FISH": "Fish",
    "FLOUR": "Flour",
    "HONEY": "Honey",
    "JAM": "Jam",
    "JUICE": "Juice",
    "MILK": "Milk",
    "NUTS": "Nuts",
    "OIL": "Oil",
    "PASTA": "Pasta",
    "RICE": "Rice",
    "SODA": "Soda",
    "SPICES": "Spices",
    "SUGAR": "Sugar",
    "TEA": "Tea",
    "TOMATO_SAUCE": "Tomato Sauce",
    "VINEGAR": "Vinegar",
    "WATER": "Water",
}
